### ISSUE TITLE
Issue with text wrapping while displaying charts in dashboard

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#450] opened 2014-01-08 12:32 UTC
The survey ID is 6174060 and the survey title
is HH OUTCOME_MONITORING in the DWA dashboard.
 For the question about the Hygienic Status of Toilet , the text in the chart is not wrapping .
![chart_display](https://f.cloud.github.com/assets/4419787/1868101/990ec2ae-7861-11e3-81f1-8376d07d500a.jpg)

The tender issue is
http://flowhelp.akvo.org/discussions/problems/379-issue-on-chart-display

**Comment by gabemart** [comment] 2015-07-16 11:47
The issue is caused by long text labels, which with the current code are positioned so that some of the label is outside the SVG element. Anything outside the SVG won't be rendered.

As far as I know, the SVG spec doesn't provide any general purpose way of wrapping text to a certain line length. As a result, I think it will be difficult to come up with a general purpose wrapping solution that prevents overlap in all circumstances.

The specific issue of the labels being positioned outside the SVG element can be fixed, however, by "manually" wrapping the text so that each line doesn't exceed a certain number of characters. This doesn't guarantee that text won't overlap other elements, but it does stop long labels from being positioned outside the SVG. 

Here's what my proposed solution looks like:

<img width="875" alt="screen shot 2015-07-16 at 12 46 21" src="https://cloud.githubusercontent.com/assets/2589977/8722059/b5f50cfa-2bb8-11e5-81d6-26aad08f4e74.png">

**Comment by muloem** [comment] 2015-07-17 09:40
@gabemart is it also possible to centre the chart? Seems there is a lot of whitespace to the right

**Comment by gabemart** [comment] 2015-07-17 10:12
@muloem I think actually moving stuff around the SVG canvas to make it more centred would be a quite a lot of work - a lot of the empty space is used when text labels are very long.

We could, however, center the SVG canvas itself, which would create a little more of a margin:

<img width="1313" alt="screen shot 2015-07-17 at 11 10 21" src="https://cloud.githubusercontent.com/assets/2589977/8745145/a6d9898c-2c74-11e5-913b-7ccbbf4ef8eb.png">
<img width="1323" alt="screen shot 2015-07-17 at 11 10 00" src="https://cloud.githubusercontent.com/assets/2589977/8745144/a6d90db8-2c74-11e5-8bf8-4670f414f10a.png">
<img width="1378" alt="screen shot 2015-07-17 at 11 10 44" src="https://cloud.githubusercontent.com/assets/2589977/8745146/a6dffeb6-2c74-11e5-8345-791faa1e4a3c.png">

It looks a bit funny for the vbar and hbar charts - perhaps I should only do this for the doughnut?

**Comment by janagombitova** [comment] 2015-07-17 10:19
I think that if we have the title of the question positioned on the left, then the charts should copy that position. (but I would keep a bit of space from the margins) And I agree with you @gabemart it does look a bit funny when they are centred.

**Comment by gabemart** [comment] 2015-07-17 10:24
I could simply add a fixed margin to the left for the doughnut chart only, that might be the simplest solution

**Comment by muloem** [comment] 2015-07-17 10:45
@gabemart true, it does look strange for everything else other than charts. I'll leave that to your discretion how final result looks.

**Comment by gabemart** [comment] 2015-07-17 13:27
Test Plan

1) Create a survey with a question group

2) Create an option question

3) Ensure that each option for the option question is greater than 28 characters long - ideally at least 56 characters long

4) Populate the question with some responses

5) Navigate to the Chart Builder and select that question

6) Generate a doughnut chart for that question

7) Verify that text to the left of the doughnut chart is not cut off - that it does not extend beyond the left-hand border of the SVG canvas

**Comment by rumca** [comment] 2015-07-23 14:54
The above test plan passes as described :+1: 

@gabemart @joycarpediem I'll close this one for now, but a few things we should perhaps think about in a future release:

* Text is cut off on doughnut charts when we have exceptionally long option answers **without** spaces:
![screen shot 2015-07-23 at 15 31 53](https://cloud.githubusercontent.com/assets/3003031/8853484/d0f43824-3152-11e5-8580-4502040e25a4.png)
* Text is still cut off for hbar charts:
![screen shot 2015-07-23 at 15 49 56](https://cloud.githubusercontent.com/assets/3003031/8853455/ac1f9e94-3152-11e5-97af-53ba0b4d8498.png)
* Text is still cut off for vbar charts:
![screen shot 2015-07-23 at 15 49 46](https://cloud.githubusercontent.com/assets/3003031/8853470/b71c0a9e-3152-11e5-929a-a1a58b4c26f3.png)

**Closed by rumca** 2015-07-23 14:54 UTC
Labels: 2 - Fixed, 3 - UI, Quick Fix

**Comment by janagombitova** [comment] 2015-08-05 12:06
On top of Ruarcc's concerns, @gabemart Gabe, I noticed that the texts in the charts happen to overlap still. It did not happen with all the charts, but with some it does, thus we need to fix it. Is this issue directly connected ti the same problems you were fixing here (wrapping), or is it caused by something else? Can you investigate please

![screen shot 2015-08-05 at 13 42 55](https://cloud.githubusercontent.com/assets/12456965/9085227/36eebc9e-3b7b-11e5-915c-713e6981d221.png)
