### ISSUE TITLE
"Question id" value when copying questions

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#807] opened 2014-09-25 16:51 UTC
When copying questions the "Question id" field is now being populated with "null_copy" as the value - even on instances where question ids are not mandatory:

![null_copy](https://cloud.githubusercontent.com/assets/3003031/4408469/16c287e6-44d4-11e4-8a28-13498015c927.JPG)

I think this could lead to some confusion amongst users, it could perhaps be a better idea if we just blank this property whilst copying?

**Comment by joycarpediem** [comment] 2015-07-13 10:06
Duplicate of #812

**Closed by joycarpediem** 2015-07-13 10:06 UTC
Labels: 1 - Defect, Quick Fix, Surveys
