### ISSUE TITLE
MINOR - 'Device group' field not populated on Assignment tab

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#470] opened 2014-03-05 17:21 UTC
When a user creates a device group, assigns a device to this group, then proceeds to the assignments tab, the below occurs:

![missingdevicegroup](https://f.cloud.github.com/assets/3003031/2335977/e110643c-a489-11e3-93e0-ded65648a6a2.PNG)

Device group in the preview is not populated correctly. However f you refresh the dashboard in between creating the group and visiting the assignments tab then it populates correctly. 

This is a non issue when you're only dealing with one device or one device group but could perhaps get confusing for users when there are lots of devices and several device groups?

**Comment by janagombitova** [comment] 2016-06-22 10:23
this is a duplicate of this newer issue https://github.com/akvo/akvo-flow/issues/1691 - closing this one

**Closed by janagombitova** 2016-06-22 10:23 UTC
Labels: 1 - Defect, 3 - UI
