### ISSUE TITLE
Include in-line help in the dashboard in more places 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1332] opened 2015-07-10 09:28 UTC
Related to https://github.com/akvo/akvo-product-design/issues/88

**Comment by gabemart** [comment] 2015-08-19 12:30
"Repeat question group" is not yet implemented in develop, so I will not add inline-help item 2 at present.

**Comment by gabemart** [comment] 2015-08-19 12:34
I have updated transifex with the new text. I will PR once the translated text has been added to transifex.

**Comment by gabemart** [comment] 2015-08-20 12:03
## Test plan

### Test languages

1) Edit a survey. Under "Survey basics", select "Show advanced settings", then tick "Enable monitoring features". Check that for each language, hovering the cursor over the '?' icon brings up the following help text:

English: "With the registration form you fill in the general information that identifies the entity you want to monitor. You fill in the registration form only once, at the beginning of your monitoring. The registration form creates the data point."

Spanish: Con el formulario de registro Ud. registrará información general que identifica la entidad que desea monitorear. Ud. rellena el formulario de registro sólo una vez, cuando empieza el monitoreo. El formulario de registro crea un nuevo punto de datos.

French: Con el formulario de registro Ud. registrará información general que identifica la entidad que desea monitorear. Ud. rellena el formulario de registro sólo una vez, cuando empieza el monitoreo. El formulario de registro crea un nuevo punto de datos.

### Test Icons Appear

**1)** i) In Edit Survey, go to Forms > Question Group > Add new question > Edit question.

ii) Set the "question type" to "Free text"

iii) Verify a help icon appears after "Use as data point name" and that, on hover, the text reads: 

"When checked, the answer to this question will become part of the ‘name’ of the data point. This will be shown in lists on the device, and can be used to search data points. This should only be enabled for one or two questions which will help to identify the data point, such as an id, or a name."

**2)** Set the question type to "Geolocation". Verify the "use as data point location" tooltip reads:

"When checked, the location captured by this question will be used as the main location of the data point."

**3)** Set the question type to "Date". Verify a help icon appears after "question type" and the text reads:

"The date format is DD-MM-YYYY."

**4)** Set the question type to "Geographic shape". Verify the help icon after "question type" has the text:

"A geographic shape can be a point, a line or a polygon which you mark on the map. This question type enables you to map a set of points, a certain area, or lines, and view that information as a layer on the map. It is useful if you want to map out an area such as a group of water taps, walking paths, a protected forest, a palm oil plantation or an urban area."

**5)** Set the question type to "Free text". Verify a help icon appears after "require double entry of answer in device". Verify the text reads: 

"In many cases you want to make sure that the collected information is correct, for example in the case of an email address, phone number or identification number, where it is easy to make mistakes when typing. Requiring the same answer to be entered twice ensures it is verified."

**6)** Set the question type to "Cascade". Verify a help icon appears after "Choose cascade resource" and the help text reads:

"Choose a pre-created cascade from the Cascade resources library. If you want to create a new cascade, you can create and publish it in the Cascade resources under the Data tab."

7) Navigate to the Devices tab. Verify a help icon appears after the column header "IMEI". Verify the help text reads: 

"The IMEI is the identifying number unique to each device that helps to identify it in our Akvo database. IMEI stands for International Mobile Station Equipment Identity number."

**Comment by rumca** [comment] 2015-09-30 23:25
All the above test cases pass as described :+1: 

@gabemart @muloem one thing which has changed, which I'm not sure if it's related to this issue or not, is that when changing the language of the dashboard (from the dropdown on the top right) the dashboard no longer auto refreshes. This means to get the strings in your selected language you have to manually refresh the page. Perhaps a quick fix we could include prior to tagging?

**Comment by gabemart** [comment] 2015-10-01 08:39
@rumca after our conversation, failed to reproduce this locally

**Comment by rumca** [comment] 2015-10-01 08:40
closing this, some sort of weird behaviour caused by one of my chrome plug-ins it would appear

**Closed by rumca** 2015-10-01 08:40 UTC
Labels: 2 - Fixed, Awaiting review
