### ISSUE TITLE
Add a usage report

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3160] opened 2019-08-08 13:37 UTC
This would let users order the "accounting"  information that is currently produced by a datascript: a table of _how many_ instances of each form were collected during a specific time period.

Fastest would be to use the current output format - a simple .CSV file, but it could also be in the form of an Excel spreadsheet.

**Comment by janagombitova** [comment] 2019-08-08 13:46
Duplicate of #2612

**Closed by janagombitova** 2019-08-08 13:46 UTC
