### ISSUE TITLE
Options reposition in Translations page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1983] opened 2017-03-10 08:28 UTC
<img width="863" alt="screen shot 2017-03-09 at 17 40 17" src="https://cloud.githubusercontent.com/assets/12456965/23787691/7b9bc88c-0573-11e7-9222-9ee22da4b9b0.png">

In some cases, when adding a translation to a form that has option questions the options are visually not on the correct spot. They are moved one line up. This is a purely cosmetic issue. 

If the user adds the translation to the option, the option shows properly in the app (where it is originally meant to be) as well as the related translation.

**Comment by janagombitova** [comment] 2017-03-10 08:42
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/technical-issue-with-akvo-database

**Comment by valllllll2000** [comment] 2017-05-18 13:51
This happenened to me while testing. I have Valeria Test > 1.9.18 UAT 1 >1.9.18 Non MF Surveys >1.9.18 All questions survey
Inside there are 2 question options: option and option no codes
![screenshot from 2017-05-18 15-42-55](https://cloud.githubusercontent.com/assets/923280/26205318/a945e0e8-3be1-11e7-85ef-8d2345c46a1d.png)
![screenshot from 2017-05-18 15-43-17](https://cloud.githubusercontent.com/assets/923280/26205317/a940abdc-3be1-11e7-850d-4d57d4702686.png)

When adding the translations:
![screenshot from 2017-05-18 15-42-10](https://cloud.githubusercontent.com/assets/923280/26205348/c6623f78-3be1-11e7-9a4f-fb4d40dad7ef.png)
you can see one of the options from "option no codes" is displayed as if it was an option of "option"

**Comment by mtwestra** [comment] 2018-01-22 16:06
@janagombitova, @valllllll2000,  I think I know the cause:

The way the translation list is built is as follows:
1) all the translation items are put in a list: combining question groups, questions, and options. The way that the system makes sure that the overall order turns out ok, irrespective of the order in which the data comes in, is by assigning it an ID. The ID is built up by using the following formula:

    questiongroupId * 1000.000 + questionId + 1000 + questionOptionId.

This way ensures that when we finally filter all the items, the order will be ok.

The bug, I think is here: the questionOptions start counting at 0, not at 1. This means that the Question and the first QuestionOption get the same ID. This means that when sorting, the result is unclear, and could result in the questionOption being shown first.

This could be fixed as follows:
On line https://github.com/akvo/akvo-flow/blob/develop/Dashboard/app/js/lib/controllers/survey-controllers.js#L1590, add a +1, so:

    order: 1000000 * qgOrder + 1000 * qOrder + parseInt(item.get('order'), 10),

becomes

    order: 1000000 * qgOrder + 1000 * qOrder + parseInt(item.get('order'), 10) + 1,

This will guarantee that the questionsOptions appear below the question, and also make sure that the order is shown to be start with 1.

**Comment by mtwestra** [comment] 2018-01-24 08:56
@muloem, just to be complete: this is the code where you can see that the questionOption order starts with zero - the index in the list is used:

https://github.com/akvo/akvo-flow/blob/develop/Dashboard/app/js/lib/controllers/survey-controllers.js#L1065-L1076

**Comment by janagombitova** [comment] 2018-02-14 08:02
@Maseline I remember in our last chat about this issue you experienced that after refreshing the page the positioning got "fixed" I tired again today and it did not work out - so the page refresh did fix the options being moved one row up. Just wanted to let you know. 

![translations](https://user-images.githubusercontent.com/12456965/36193306-b2a67aa8-1165-11e8-88e4-e86767c50359.gif)

**Comment by Maseline** [comment] 2018-02-20 07:13
Test plan
Navigate to a survey with existing questions and move options questions positions
Select manage translations, the question options should appear below their respective questions in the correct order.

**Comment by kymni** [comment] 2018-11-07 08:58
#2498 fixes this issue but the overall translations front-end code needs a major refactor

**Comment by janagombitova** [comment] 2018-11-14 11:21
The options do not reposition anymore but the order number now starts at 0 every time. Do we need to show the order numbers in the UI in the 1st place considering we do not show them in the form editor?

![screen shot 2018-11-14 at 12 20 15](https://user-images.githubusercontent.com/12456965/48479472-b0988200-e807-11e8-8641-d5eae161f4e0.png)

**Comment by kymni** [comment] 2018-11-14 13:17
Other than displaying to the user the order of options, I don't feel showing it has any additional value. It is however a minor fix so we can keep it for now

**Comment by janagombitova** [comment] 2018-11-14 14:02
Wonderful! It is brilliant now

**Closed** 2018-11-15 07:31 UTC
Labels: Ready for release, UI
