### ISSUE TITLE
Better timezone handling in export raw data reports

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#257] opened 2013-06-18 07:44 UTC
Currently, raw data reports are exported with times in UTC. From the users perspective, this is not very logical, as the data has been collected in a specific timezone. This especially is cumbersome when a count is needed for the amount of surveys collected on a certain date.

**Comment by ichinaski** [comment] 2016-02-15 12:41
Date question type issues
=======

I'm gathering all issues around this topic and closing the rest, so we have a common place to discuss a fix for them (they are closely related to each other).

# Better timezone handling in export raw data reports

Currently, raw data reports are exported with times in UTC. From the users perspective, this is not very logical, as the data has been collected in a specific timezone. This especially is cumbersome when a count is needed for the amount of surveys collected on a certain date.

# Trim down timestamp a date inside the raw data report (https://github.com/akvo/akvo-flow/issues/1496)

When answering a date questions in the app you only see a date. In the raw data report a timestamp is included.

Current situation
04-11-2015 01:12:32 CET

Desired situation
04-11-2015

# QuestionAnswers of type DATE are stored as both timestamps and formatted date strings (https://github.com/akvo/akvo-flow/issues/1139)

QuestionAnswers stored as formatted date strings results in NumberFormatExeptions when doing raw data reports

**Comment by ichinaski** [comment] 2016-02-16 12:29
My proposal for this issue is to use `yyyy-MM-dd` in the question response format, instead of a timestamp. After all, this is a **date** question, and that's the sought after value in this context. This date can be further formatted for reports or other UIs if that's necessary.

**Comment by janagombitova** [comment] 2016-03-09 13:25
One more existing issue related to date format is raw data reports

# Change time format in questionId - exported reports to ISO 8601 (https://github.com/akvo/akvo-flow/issues/846)

At the moment, we export dates in the raw data report in a custom format.

The reports which use the questionIds as column headers is used for import to other systems. Therefore, it is important to have a standard format for the time. The proposal is to use ISO 8601, which gives times the following shape: 2014-10-08T20:27:16+00:00.

**Comment by ichinaski** [comment] 2016-03-23 11:00
**Test plan:**
 *TODO*

**Comment by ichinaski** [comment] 2016-03-31 16:57
**Test plan:**

*Note: There are some strange issues in the datepicker layout. We need to figure out what's the cause of them*

* Create a form with date questions
* Provide answers using the app
* Dashboard:
    * VIsualise and edit data in the dashboard.
* Reports:
    * Export data. Ensure format used for question responses is YYYY-MM-DD. Submitted date should keep the time.
    * Update some date values, and import the data. Values should be updated in the data tab

**Comment by rumca** [comment] 2016-04-20 10:57
@ichinaski found a slightly weird issue in this. Everything works as expected when you submit data, view it in the inspect data tab, edit in inspect data tab etc. However when you perform some data cleaning and then upload the data, the values in the reports are updated correctly, but in the dashboard they are displayed as the date -1:

![screen shot 2016-04-20 at 11 28 02](https://cloud.githubusercontent.com/assets/3003031/14672317/febce22a-06ee-11e6-8aa3-2dab2f248c0d.png)

**Comment by rumca** [comment] 2016-04-20 13:09
Fix looks good 👍

**Closed by rumca** 2016-04-20 13:09 UTC
Labels: 1 - New Feature, 2 - Fixed, 3 - Backend, 3 - Field Survey App, 3 - UI

**Comment by rumca** [comment] 2016-04-20 15:04
Found a compatibility issue which is presumably related to these changes. Now that the datepicker results in dates in the format of YYYY-MM-DD and not YYYY/MM/DD the filter option on the reports tab no longer works. 

FLOW services expects the old date range and therefore doesn't correctly select only responses for the range provided. I guess we just need to add support for the new format (whilst also handling the old).
