### ISSUE TITLE
Raw data exports do not reflect up-to-date data point names 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2160] opened 2017-06-20 11:06 UTC
The user defines what builds the data point name. However many times the users realise after a while that other information is more helpful to have in the name to identify data points. So they change the data point name definition. They make another question to build the name,  data clean the answers, remove an existing one or fully add a new question (can do anything). After syncing the data points in the app the changes are shown and before today (approximate day) this change was also reflected in the data exports. Not anymore. 

Here are the steps the user takes and what she sees: 

1. User creates a form and defines what builds the data point name (free text question) 
1. User captures data 
1. User exports data (registration form) and the name is shown correctly 
1. User makes a change to what builds the data point name (added the number question as well) 
1. User collects new data on the app and the name is shown and built correctly
1. User syncs the data on the app and **all** the data points now show with the updated version of the name (text+number)
1. User goes into the browser, on the monitoring tab the data point names show updated 
1. User exports data (registration form) and sees the names show their first version, so not the updated one after syncing (old points that were created with the first definition of the name have the first version of the name, not the 2nd updated one even though on the app in the list of points they show updated.  

Example: 

Screen shot of the updated data point name in the app and from the export. 

![screenshot_2017-06-20-13-38-23](https://user-images.githubusercontent.com/12456965/27331468-dd300fb4-55bd-11e7-8ac6-6dbff8a7c4a9.png)

<img width="637" alt="screen shot 2017-06-20 at 13 37 13" src="https://user-images.githubusercontent.com/12456965/27331416-9f608cb8-55bd-11e7-8a3a-470b8c2d2fdd.png">

**Comment by janagombitova** [comment] 2017-06-20 11:08
Here is an issue and a fix where we know for sure that it was still working: https://github.com/akvo/akvo-flow/issues/1934

**Comment by stellanl** [comment] 2017-06-20 12:14
In the database, we see that the new names are set for the SurveyedLocation entities but not for the old surveyInstance entities.

**Comment by stellanl** [comment] 2017-06-20 12:16
One solution is to make the exporter get the name from the SurveyedLocation.

**Comment by stellanl** [comment] 2017-06-21 08:26
Test plan:
* Change the name-generating questions for a form with data.
* Publish the form.
* Wait a few minutes for the background point renaming to 
complete.
* Make a raw data report; the name column should have updated.

**Comment by janagombitova** [comment] 2017-06-26 10:58
@stellanl will this issue https://github.com/akvo/akvo-flow/issues/1743 we also resolved with the fixes here?

**Comment by stellanl** [comment] 2017-06-26 12:29
Possibly not, if that was really caused by the backend running out of time. We should test once we have deployed.
The script will fix up anything left behind, though.

**Comment by muloem** [comment] 2017-06-28 14:57
@janagombitova @stellanl I have changed the milestone on this one because the code is not yet merged and also because the current solution would increase the number of reads and writes to the datastore.  We will have to come up with a solution that doesn't add more traffic to the datastore

**Comment by stellanl** [comment] 2017-06-28 21:23
This way there will be more datastore traffic when you publish.
The other way is to never use the name from the SurveyInstance at all, which will mean more datastore traffic when you generate a report.

**Comment by stellanl** [comment] 2017-07-04 14:24
The third route is to never store the 'composed' display name at all. That means changes in these endpoints:

/rest/surveyed_locales <-- Dashboard UI (GET/DELETE)
	org.springframework.web.servlet.DispatcherServlet --> org.waterforpeople.mapping.app.web.rest.SurveyedLocaleRestService
	Only lists surveyedLocales, never reads questions or answers.
	Need to read all questions (or filtered by localeNameFlag) and all corresponding answers.
	Or it can all be done in the UI, probably without changing anything in the backend.

/surveyedlocale <-- app
	org.waterforpeople.mapping.app.web.SurveyedLocaleServlet
	We loop on all the surveyalValues, but the localeNameFlag bit is not stored there, so would need to fetch the questions, too.

/surveyinstance or /instancedata <-- reporting
	org.waterforpeople.mapping.app.web.SurveyInstanceServlet
	Report engine already fetches all the questions and all the answers, so adds no extra datastore traffic.

**Comment by stellanl** [comment] 2017-07-04 14:26
The fist step could be to have the report engine compose the display name itself. That would remove the update bug.
Then as a second step we might change the other two places, which would lessen the cost of publishing a survey.

**Comment by stellanl** [comment] 2017-07-12 23:42
Test plan:
Pick any survey that has data collected for it.
Generate a report.
Change which question(s) is/are contributing to the display name.
Generate a report. (Remember to change the date so you do not get a cached copy.)
The new report should have different display names.

**Comment by janagombitova** [comment] 2017-07-19 09:11
👍  data point name changes are reflected in exports!

But only for the registration from exports, as the problem of the data point names missing in the Display name column for monitoring form exports is back again https://github.com/akvo/akvo-flow/issues/1762

**Comment by muloem** [comment] 2017-07-19 11:44
@stellanl this exception pops up in the log files. I guess that library is not imported when building flow services.

```
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.waterforpeople.mapping.domain.QuestionAnswerStore.getDatapointNameValue(QuestionAnswerStore.java:207)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.constructDisplayName(GraphicalSurveySummaryExporter.java:737)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.writeInstanceData(GraphicalSurveySummaryExporter.java:605)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.fetchAndWriteRawData(GraphicalSurveySummaryExporter.java:551)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.export(GraphicalSurveySummaryExporter.java:397)
	at akvo.flow_services.exporter$export_report.invoke(exporter.clj:58)
	at akvo.flow_services.scheduler.ExportJob.execute(scheduler.clj:52)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
```

**Comment by janagombitova** [comment] 2017-07-21 08:26
👍  works like a charm! Well done

**Comment by janagombitova** [comment] 2017-07-26 08:39
👍 it all works fine on UAT1, lets see give it a go in the real world

**Closed** 2017-07-27 06:44 UTC
