### ISSUE TITLE
Use metadata field on data point as partitioning key for download

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#848] opened 2014-10-09 16:02 UTC
At the moment, when an enumerator downloads data, he/she downloads all the data on the project. However, in many cases, project managers prefer to give enumerators access only to a subset of the data. 

As an example, consider the case of Ghana. Surveys are defined per region. But the monitoring will be done on district level, so the project manager prefers to give access to change data only on the district level. But at the moment only the data for the whole region can be downloaded.

One way to solve this would be to put an addition piece of meta-data on the datapoint, just like the displayName that we have now. This meta data could be filled by a question in the survey, for example 'district'. Then access to the data could be partitioned based on this meta-data field.

**Comment by janagombitova** [comment] 2019-04-05 06:41
duplicate of #2796

**Closed by janagombitova** 2019-04-05 06:41 UTC
