### ISSUE TITLE
Survey page loading errors 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2821] opened 2018-08-17 07:01 UTC
We have received a message from a user in Haiti having issues with loading his Flow instance, the survey page. I have tested opening up larger Flow instances on my normal network connection and had the same issue. Below are the errors I see in Console. 

<img width="1164" alt="screen shot 2018-08-17 at 08 59 25" src="https://user-images.githubusercontent.com/12456965/44252331-128f1e80-a1fc-11e8-89dc-acad9498da10.png">
<img width="1162" alt="screen shot 2018-08-17 at 08 59 40" src="https://user-images.githubusercontent.com/12456965/44252333-14f17880-a1fc-11e8-8ad6-16d024792bd3.png">
<img width="1164" alt="screen shot 2018-08-17 at 08 59 55" src="https://user-images.githubusercontent.com/12456965/44252334-14f17880-a1fc-11e8-8ea8-411d3c25352c.png">
<img width="1163" alt="screen shot 2018-08-17 at 09 00 07" src="https://user-images.githubusercontent.com/12456965/44252335-158a0f00-a1fc-11e8-9500-45e16bee5352.png">
<img width="1162" alt="screen shot 2018-08-17 at 09 00 19" src="https://user-images.githubusercontent.com/12456965/44252339-17ec6900-a1fc-11e8-9e54-1bbabfa627f1.png">
<img width="1156" alt="screen shot 2018-08-17 at 09 00 28" src="https://user-images.githubusercontent.com/12456965/44252340-17ec6900-a1fc-11e8-8c33-cab0953d7424.png">
<img width="1161" alt="screen shot 2018-08-17 at 09 00 41" src="https://user-images.githubusercontent.com/12456965/44252341-1884ff80-a1fc-11e8-8682-6c2f332bd7d1.png">

**Comment by kymni** [comment] 2018-08-21 12:47
## Test plan
Confirm error no longer shows

**Comment by janagombitova** [comment] 2018-08-21 12:51
No error showing in logs on uat1

**Comment by janagombitova** [comment] 2018-08-23 05:45
As agreed after the release I tested out the loading on few larger instances and smaller ones. On these instances I did not get any errors in console and the loading spinner stopped: 
https://lifewater.akvoflow.org/admin/
https://pilots.akvoflow.org/admin/ 
https://welthungerhilfe.akvoflow.org/admin/
https://greencoffee.akvoflow.org/admin/

But on others the error shows causing loading to not stop. Here are some instances and a screen shot. Here are some examples:

https://icco.akvoflow.org/admin/ 
<img width="1247" alt="screen shot 2018-08-23 at 07 35 36" src="https://user-images.githubusercontent.com/12456965/44506571-3f817c80-a6a7-11e8-8e97-572d36dc1b36.png">

https://ssh4a.akvoflow.org/admin/
<img width="1104" alt="screen shot 2018-08-23 at 07 40 02" src="https://user-images.githubusercontent.com/12456965/44506701-d8b09300-a6a7-11e8-9714-98086e313fa2.png">

https://wfp.akvoflow.org/admin/
<img width="952" alt="screen shot 2018-08-23 at 07 45 01" src="https://user-images.githubusercontent.com/12456965/44506843-81f78900-a6a8-11e8-97ca-daa79f21b89e.png">

So this issue is still present and needs to be handled

**Comment by kymni** [comment] 2018-08-23 08:06
It appear this error is being caused by orphan forms. When loaded, forms attempt to get the parent survey's name. If the parent survey no longer exists, the error occurs. After we enabled the surveys endpoint to run on dashboard-load in #2754, we pull all forms into the local datastore. This includes forms whose parent surveys may no longer exist hence the error.

We can attempt to fix this by creating a check for orphan forms on the front-end but a more permanent solution is to clean the data store and remove orphan forms

**Comment by kymni** [comment] 2018-09-04 08:15
This should be closed as it was addressed during hotfix 1.9.36.1

**Closed** 2018-09-13 09:11 UTC
