### ISSUE TITLE
Wrap long titles in charts

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1063] opened 2015-01-08 11:09 UTC
In charts, long titles fall of the screen, as shown in the image below. 
![screen shot 2015-01-08 at 12 08 38](https://cloud.githubusercontent.com/assets/478954/5661718/3cb83c68-972f-11e4-976a-ec5327c63637.png)

Proposed solution: wrap long titles.

**Comment by joycarpediem** [comment] 2015-07-13 07:30
Duplicate of #450

**Closed by joycarpediem** 2015-07-13 07:30 UTC
Labels: 1 - Defect
