### ISSUE TITLE
Feature Request: Associated Repeatable Questions

### ISSUE THREAD

**Issue by bhmann** [akvo/akvo-flow#269] opened 2013-06-28 19:43 UTC
If numerical dependencies become a new feature, having those dependencies linked to repeatable questions would be a great way to cut down on the number of questions someone has to build into a survey.

For example, when doing a water point survey, a question (call it [Q1]) is asked "How many water samples were taken?" A photo is needed for each individual water sample, showing the quality of water at the time of collection, or maybe a barcode question is needed to link each sample with the water point (call it [Q2]). Using the numerical dependencies linked with associated repeatable questions, the appropriate number of follow-up [Q2] questions appear based upon your answer to [Q1]. If you responded "3 samples", then 3 [Q2] questions appear to collect the barcodes or photos for each sample.

Through this process, less training is required for enumerators to collect more complex data while survey creators can make sure required information is gathered.

**Comment by ichinaski** [comment] 2015-01-27 16:15
Relevant documents for the feature:
* [Functional design](https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/FunctionalDesign.md)
* [Technical design](https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/TechnicalDesign.md)
* [Visual design](https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/35-RepeatQuestionGroups/VisualDesign.md)

**Comment by ichinaski** [comment] 2015-02-25 12:38
Question not belonging to the same group cannot depend on a repeatable group's questions. Allowed dependencies:
  * [x] Repeatable question on an external group question
  * [x] Repeatable question on a repeatable question **within the same group**
  * [ ] External question (different group) on a repeatable question

When prompting the dependency question dropdown, we need to ensure the aforementioned requirements are fulfilled.

**Comment by ichinaski** [comment] 2015-06-16 10:39
## Dashboard integration

* Add `repeatable` flag on question groups: This is a fairly trivial action but depends on some aesthetic changes. For the moment being there's a temporary implementation that does the trick to set this flag, though is just squeezed in the existing layout. Perhaps @loicsans has a better understanding of this UI issue.

* Code management: Issue **authenticated** requests to flow-services, and perform CRUD operations for managing codes. This feature belongs initially on the *Devices* tab, though it's UI/UX is pretty much the same as the API key management in the *Users* tab. For bringing about this task's auth part, we need to make use of the JWT claims, specifying which instances the user has access to.

**Comment by muloem** [comment] 2015-09-03 08:04
#### Test Plan


##### Test 1: Repetable Question group creation 

1. Create a new survey and add a new question group.

2. The user should see the possibility to set a group as a repeatable question group

3. Save the question group

##### Test 2: Repeatable question group updating

1. Refresh the dashboard and edit the question group selected previously.  Deselect the repeatable question group setting and save the survey.

2. Reopen the group and the option should be deselected

##### Test 3: Copy repeat question group 

1. Copy the repeat question group within the same survey on the dashboard

2. Ensure that the copy worked correctly

##### Test 4: Survey publishing serialization 

1. Publish the survey with the repeatable question groups and assign it to a device

2. Check on the device that when responding to questions in that group the repeat option is given


##### Test 5: Data Submission / File processing and viewing

1. Enter a number of responses for the survey with repeat questions and submit the data to the dashboard.

2. After making sure that the responses are marked as submitted, check the dashboard via the inspect data tab to see that the responses are correctly shown and rendered

##### Test 6: Data updating

1. Edit some of the responses for the repeatable question responses and save them

2. Refresh the dashboard and search for the edited responses check that expected edits are correctly saved

##### Test 7: Data deleting

1. Delete responses from some of the repeatable questions

2. Refresh the dashboard and ensure that the deletions worked correctly

**Comment by ichinaski** [comment] 2015-09-03 08:46
@muloem I just noticed the dashboard allows you to setup a dependency on a repeatable group's option question. I seem to remember we agreed on this not being enabled?

**Comment by janagombitova** [comment] 2015-09-04 11:22
@ichinaski yes we agreed that you cannot make a question (outside the repeated group) dependent on a question within the group.

**Comment by rumca** [comment] 2015-10-01 00:01
@muloem everything looks good except **Test 2: Repeatable Question group dependency** - from what I can see it's possible to set up a question group which contains a question that is dependent on an option question in a repeatable group. See https://akvoflow-uat1.s3.amazonaws.com/surveys/36849115.xml

**Comment by rumca** [comment] 2015-10-01 00:04
I was gong to create a new issue for a future release to address this minor UI problem, but maybe https://github.com/akvo/akvo-flow/commit/102616f8232c883a7d8f32ac45e08003b50554ab is responsible for the save button appearing as follows:

![screen shot 2015-09-30 at 09 22 14](https://cloud.githubusercontent.com/assets/3003031/10209885/51a56b9e-67d8-11e5-95f2-bf95eb74ea74.png)

**Comment by rumca** [comment] 2015-10-01 11:43
The fix for Test Case 2 looks good :+1: 

I'll add a new issue to address the small UI hiccup.

**Comment by rumca** [comment] 2015-10-01 14:56
@muloem previously the popup when you click view details on the monitoring tab looked as follows:

![screen shot 2015-10-01 at 15 49 06](https://cloud.githubusercontent.com/assets/3003031/10224065/34121f06-6854-11e5-8eaa-393890843ae8.png)

now the first time you click view details on an item in the list, the pop up looks as follows:

![screen shot 2015-10-01 at 15 51 38](https://cloud.githubusercontent.com/assets/3003031/10224100/5e21669e-6854-11e5-8e6d-a537792bcf0c.png)

and then when you click to view details on a specific item  (which should look like the first picture)

![screen shot 2015-10-01 at 15 53 37](https://cloud.githubusercontent.com/assets/3003031/10224166/9a558442-6854-11e5-904a-8db13e7d088f.png)

It looks like you can only view the values on the bottom most response?

![screen shot 2015-10-01 at 15 54 20](https://cloud.githubusercontent.com/assets/3003031/10224177/b2d99418-6854-11e5-8923-73b91e3dd66e.png)

Also when you go back to the first list on the monitoring tab, and then click to view details on a different suveryed locale the Question Answer table in the popup is already prepopulated before you click anything.

**Comment by rumca** [comment] 2015-10-05 09:09
Expected behaviour on monitoring tab restored :+1:

**Comment by muloem** [comment] 2015-10-22 08:45
For the test plan regarding **RQG import** look at the issue #1421

**Comment by muloem** [comment] 2015-10-22 12:31
@janagombitova do we already have documentation for the repeat question groups import?

**Comment by janagombitova** [comment] 2015-10-23 12:31
No we don't, but I can type it down. What are the 'warnings' (things the user should not mess around with when importing) that I should add? @jonase @muloem

**Comment by rumca** [comment] 2015-11-02 01:48
@jonase any idea what's causing the below from the logs on flowdev1?

```
Could not invoke rest services: java.io.IOException: Server returned HTTP response code: 500 for URL: http://uat1.akvoflow.org/rawdatarestapi
java.io.IOException: Server returned HTTP response code: 500 for URL: http://uat1.akvoflow.org/rawdatarestapi
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at org.waterforpeople.mapping.dataexport.service.BulkDataServiceClient.fetchDataFromServerPOST(BulkDataServiceClient.java:1147)
	at org.waterforpeople.mapping.dataexport.service.BulkDataServiceClient.fetchDataFromServer(BulkDataServiceClient.java:1102)
	at org.waterforpeople.mapping.dataexport.service.BulkDataServiceClient.fetchDataFromServer(BulkDataServiceClient.java:1084)
	at org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter.invokeUrl(RawDataSpreadsheetImporter.java:533)
	at org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter$1.run(RawDataSpreadsheetImporter.java:513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by muloem** [comment] 2015-11-04 11:01
@janagombitova Could you include something in the documentation about having to include the numbers in the repeat column?

**Comment by janagombitova** [comment] 2015-11-04 12:08
@muloem yes. will do today/tomorrow

**Comment by rumca** [comment] 2015-11-05 10:11
Closing this for now - all current work completed and tested.

**Closed by rumca** 2015-11-05 10:11 UTC
Labels: 1 - New Feature, 2 - Fixed
