### ISSUE TITLE
Differentiate between dialogue messages

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#787] opened 2014-09-22 12:51 UTC
At the moment the styling of the dialogue box shown to communicate to users is the same regardless of whether the message is an error, a request for confirmation of input, or simply information to the user that that their action was successful.  See examples below.  It would help user interaction to differentiate between especially errors and other kinds of dialogue messages, e.g by highlighting with red colour or a warning sign.

Warning that survey will not be saved:
![screen shot 2014-09-22 at 14 45 59](https://cloud.githubusercontent.com/assets/533336/4356212/ec0e1260-4256-11e4-9e42-b9b0c6535ab7.png)

Confirmation that a question has been deleted:
![screen shot 2014-09-22 at 14 46 44](https://cloud.githubusercontent.com/assets/533336/4356219/02afa93e-4257-11e4-961f-53f09cc2a0ef.png)

**Comment by janagombitova** [comment] 2016-12-01 16:10
duplicate of https://github.com/akvo/akvo-flow/issues/1853

**Closed by janagombitova** 2016-12-01 16:10 UTC
