### ISSUE TITLE
Cartodb custom maps - when viewing or editing a custom map, the custom maps tab should be highlighted

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1677] opened 2016-05-17 08:51 UTC

**Comment by janagombitova** [comment] 2016-06-09 08:22
@kymni is this still an issue? I could not reproduce it anymore when testing on UAT1

**Comment by kymni** [comment] 2016-06-09 08:27
@janagombitova already fixed it

**Comment by janagombitova** [comment] 2017-04-06 14:19
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.

**Closed by janagombitova** 2017-04-06 14:19 UTC
Labels: 1 - Maps
