### ISSUE TITLE
Arrows for navigating in calendar do not always show

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1245] opened 2015-04-17 12:03 UTC
The arrows that enable navigating months on the calendar do not always show. So far this has been observed when using the Firefox (35.0.1) browser .

![screen_shot_2015-02-24_at_10 12 49_am](https://cloud.githubusercontent.com/assets/533336/7201684/60afdf3a-e50a-11e4-8bb2-8a54bc9639c3.png)

**Comment by gabemart** [comment] 2015-07-10 11:07
@muloem I am not able to replicate in FF on Ubuntu or OSX. I suspect this issue may be caused by the sprite failing to load - i.e. it may be caused by a network problem or timeout

**Comment by gabemart** [comment] 2015-07-15 11:21
With help of @rumca was able to reproduce on some pages. This issue is also covered by #809

**Comment by gabemart** [comment] 2015-08-07 09:06
Specifically, the request for `/admin/css/custom-theme/images/ui-icons_454545_256x240.png` returns a 404. The file exists at `/Dashboard/app/css/custom-theme/images/ui-icons_454545_256x240.png`.

Further testing shows that every file in that folder returns a 404. Trying to navigate to `/admin/css/custom-theme/images` in the browser also returns a 404 where I would expect it to return a 403. '/admin/css/custom-theme/' returns a 403 as expected.

Permissions for the `images` directory look correct (`drwxr-xr-x`). At present I'm not sure what is causing the problem.

**Comment by gabemart** [comment] 2015-08-07 09:10
This is fully covered by #809 so I am going to close this issue and move discussion there.

**Closed by gabemart** 2015-08-07 09:10 UTC
Labels: 3 - UI, Quick Fix
