### ISSUE TITLE
Specific users not able to assign permissions to other users

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1416] opened 2015-09-28 14:30 UTC
- For specific users the folder list is empty when assigning permissions
- Contact Geert for screenshots (contains user info)

**Comment by akvotender** [comment] 2015-09-28 14:31
Assigned to [Tender discussion #5919](http://flowhelp.akvo.org/help/discussions/problems/5919-new-user-role).

**Comment by akvotender** [comment] 2015-09-28 14:32
Assigned to [Tender discussion #5889](http://flowhelp.akvo.org/discussions/problems/5889-user-loggedin-problem).

**Comment by akvotender** [comment] 2015-09-28 14:58
Assigned to [Tender discussion #5933](http://flowhelp.akvo.org/discussions/problems/5933-fwd-akvo-flow).

**Comment by akvotender** [comment] 2015-10-08 12:59
Assigned to [Tender discussion #5993](http://flowhelp.akvo.org/discussions/problems/5993-user-tab).

**Comment by akvotender** [comment] 2015-11-03 14:40
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/test-multiple-e-mail-participants
Assignee: Geert Soet

Message:
-- 
Met vriendelijke groet,

**Comment by akvotender** [comment] 2015-11-04 06:12
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-4617-from-geert-at-akvo-dot-org
Assignee: Joy Ghosh

Message:
[AKVOFLOW] Support request #4,617 from geert@akvo.org 

Geert Soet (https://akvoflow.supporthero.io)   


User email: geert@akvo.org 
 Request Info 
Device:  Personal computer 
Browser:  Chrome 46.0.2490.71 
OS:  OS X 10.10.5 
IP Address:  95.97.154.90 
URL:  https://akvoflow.supporthero.io/content 
 User name 
geert 
 Request Info 
where is chard? 

Notification sent by Supporthero.io - 10/29/15 10:07 AM (http://www.supporthero.io)

**Comment by akvotender** [comment] 2015-11-20 11:02
Giel having the same issue.

**Comment by janagombitova** [comment] 2015-12-09 16:12
@Geerts can you share more details about this issue? The links are not working for me. Could this be because the user does not have a form associated to his roles?

**Comment by Geerts** [comment] 2015-12-09 16:26
HI Jana,

We have checked if they have the right permissions and they have. @muloem , you said before it had to do with some upgrade Ember did right?

**Comment by janagombitova** [comment] 2015-12-11 09:14
This issue has also been brought up by Welthungerhilfe and it seems that: If I have a role linked to only one folder/or a few, but not All folders, and I can create and manage users, in the dropdown when selecting the folder for the role, the dropdown is empty. 

![screen shot 2015-12-11 at 10 05 39](https://cloud.githubusercontent.com/assets/12456965/11740013/f683382c-9fef-11e5-9849-6110cd2d2a6f.png)

At this moment the dropdown shows the folder only when I have All folders assigned to my role. 

The expected behaviour is: I see in the dropdown **only** the folders that are assigned to me.

**Comment by jonase** [comment] 2015-12-11 12:00
## Test Plan

* Create a user that
  * Has the permission to "Administrator - Create, Modify and Delete Users"
  * Does *not* have access to the root folder (All surveys and folders)
  * Do have access to one or several sub folders
* Login as that user and visit the Users tab
  * Pick a user and click "Edit" to visit the user details page
  * Make sure that you can select *only* the folders that the logged in user has access to.

**Comment by rumca** [comment] 2016-01-04 23:14
Test plan passes as described.

**Closed by rumca** 2016-01-04 23:14 UTC
Labels: 1 - Bug, 2 - Fixed
