### ISSUE TITLE
Raw Data Reports don't handle all languages correctly

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1457] opened 2015-10-27 16:13 UTC
Responses are rendered as `???` for at least *Khmer* and *Vietnamese* languages (and probably others as well). We need to ensure proper encoding/decoding when transferring data from GAE to flow-services.

**Comment by jonase** [comment] 2015-10-27 16:19
## TestPlan

* Create some responses with *Khmer* and/or *Vietnamese* characters
* Export the report. The report should correctly render the characters and not just display question marks such as `??? ??`.

**Comment by akvotender** [comment] 2015-10-28 15:38
Assigned to [Tender discussion #6121](http://flowhelp.akvo.org/discussions/problems/6121-data-download).

**Comment by janagombitova** [comment] 2016-01-19 14:03
Based on Jonas's message: This first commit is part of the codebase since 1.9.2 but the second commit is not. I think we should close it and reopen if we get a bug report. The first commit did fix the issues as far as I can remember > closing this issue

**Closed by janagombitova** 2016-01-19 14:03 UTC

**Comment by muloem** [comment] 2016-01-20 06:02
Confirmed. The issue is fixed. :+1:
