### ISSUE TITLE
Assignments minor color adjustment

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3364] opened 2019-12-18 14:51 UTC
The assignments work perfectly just one minor detail, see screenshot:
![Screenshot from 2019-12-17 11-35-29](https://user-images.githubusercontent.com/923280/70988065-6ac08400-20c1-11ea-9593-6f07eae6c7fb.png)
This is slightly different from the original mockup in a way that once the section is selected, for instance forms, the text should be black. But in the current implementation the text is always blue. If I understand correctly blue means selectable but since we already selected it it should not be "selectable". This is a minor cosmetic issue, feel free to open another issue for it as I do not think this should block the release.

_Originally posted by @valllllll2000 in https://github.com/akvo/akvo-flow/issues/3297#issuecomment-566485165_

**Comment by marvinkome** [comment] 2020-01-20 09:43
Is this related to #3376

**Comment by janagombitova** [comment] 2020-04-09 12:21
Duplicate of https://github.com/akvo/akvo-flow/issues/3503

**Closed by janagombitova** 2020-04-09 12:21 UTC
Labels: 1 - Assignment, UI
