### ISSUE TITLE
Copying Monitored surveys doesn't set up registration form correctly

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1279] opened 2015-05-14 18:00 UTC
@muloem noticed this on the most recent round of testing - it's vaguely related to #1267 

When you copy a monitoring survey the registration form is not set up correctly in the copied survey. For example I see the below in a copied survey (neither form is set as a reg form):

![screen shot 2015-05-14 at 18 37 36](https://cloud.githubusercontent.com/assets/3003031/7637952/768f5078-fa69-11e4-9435-bf030ac4af31.png)

If I publish the two forms above, then the `registrationSurvey` id property is set to the ID of the registration form from the original survey I used to create the copy. Therefore when copying surveys we need to update the `registrationSurvey` id property to point to the new copy of the original registration form. 

Note that in the copied survey, when I click advanced settings the Registration form is then set to whichever form name comes alphabetically first - which could lead to confusion. Perhaps something to keep an eye out for when reviewing tender issues between now and the next release?

**Comment by muloem** [comment] 2015-08-06 05:53
Feedback from a support request connected to this issue seems to suggest the possibility that wrongly copied registration forms is the root cause of some non-monitoring surveys having multiple forms.

**Comment by akvotender** [comment] 2015-08-13 08:04
Assigned to [Tender discussion #5658](http://flowhelp.akvo.org/discussions/problems/5658-registration-form-glitch-in-pacificwashakvofloworg).

**Comment by stellanl** [comment] 2016-06-15 15:38
Tested ok on my Linux dev machine

**Comment by stellanl** [comment] 2016-06-15 15:55
Test plan:
1. Find or create a monitoring survey with at least 2 forms.
2. Set registration form to the second form.
3. Copy the survey.
4. Verify that the registration form of the copied survey is the second form.

**Comment by janagombitova** [comment] 2016-06-16 06:42
Hi @stellanl opening this issue, so we do not forget to test it. Will close it once all issue tests and regression tests are done

**Comment by muloem** [comment] 2016-06-29 13:57
@stellanl I would include as part of the test plan, an assignment to a device and confirm that the copied survey doesn't show greyed out forms.

**Comment by janagombitova** [comment] 2016-06-30 12:31
👍 passes test plan (on both dashboard and app)

**Comment by janagombitova** [comment] 2016-07-09 14:31
passed regression tests as well 👍

**Closed by janagombitova** 2016-07-09 14:31 UTC
Labels: 0 - Priority 1, 1 - Bug, 2 - Fixed
