### ISSUE TITLE
Incorporate codes in cascade resource

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1209] opened 2015-03-26 07:41 UTC
At the moment, we don't serialize cascade codes into the cascade resource. To make this consistent with the options, we should:
1) serialize the codes in the cascade resource
2) return the codes together with the values in the answers provided by the device.

**Comment by janagombitova** [comment] 2015-07-02 06:22
Duplicate of #1323

**Closed** 2015-07-02 06:22 UTC
Labels: 1 - Feature Change
