### ISSUE TITLE
Question groups duplicated without user involvement

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1417] opened 2015-09-28 15:01 UTC
- Users experience duplicated question groups in their survey

**Comment by akvotender** [comment] 2015-09-28 15:02
Assigned to [Tender discussion #5929](http://flowhelp.akvo.org/discussions/problems/5929-fwd-problem-with-a-specific-survey-and-again-slow-flow-dashboard).

**Comment by Geerts** [comment] 2015-09-28 15:03
- When trying to delete a question group it returns.

**Comment by akvotender** [comment] 2015-10-06 11:29
Assigned to [Tender discussion #5969](http://flowhelp.akvo.org/discussions/problems/5969-getting-only-translations-in-raw-data-report).

**Comment by muloem** [comment] 2015-10-12 10:02
The duplication of question groups appears to have been caused by a timeout when processing tasks in the backend. The time out resulted in the duplicated question groups being created but not saved with the link to then newly copied survey.

**Comment by akvotender** [comment] 2015-10-15 10:22
Assigned to [Tender discussion #6027](http://flowhelp.akvo.org/discussions/problems/6027-copying-icon-continuously-running).

**Comment by muloem** [comment] 2015-10-26 13:54
### Test Plan

1. Create a survey with lots of option questions e.g 25 each with lots of options 100 options per question

2. Copy the survey and check to ensure that it all copies and all groups in the copied survey do not remain with the *Copying* spinner showing i.e copying completed.

**Comment by rumca** [comment] 2015-11-02 10:40
@muloem I totally misread this test plan and ended up creating 50 questions with 100 options each - the subsequent copy fails and throws an exception for both surveys:

```
/rest/questions
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:825)
...
	at com.gallatinsystems.survey.dao.TranslationDao.findTranslations(TranslationDao.java:71)
	at com.gallatinsystems.survey.dao.QuestionOptionDao.listOptionByQuestion(QuestionOptionDao.java:53)
	at org.waterforpeople.mapping.app.web.rest.QuestionRestService.listQuestions(QuestionRestService.java:135)
...
C 2015-11-02 11:23:13.623
Uncaught exception from servlet
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:825)
...
	at com.gallatinsystems.survey.dao.TranslationDao.findTranslations(TranslationDao.java:71)
	at com.gallatinsystems.survey.dao.QuestionOptionDao.listOptionByQuestion(QuestionOptionDao.java:53)
	at org.waterforpeople.mapping.app.web.rest.QuestionRestService.listQuestions(QuestionRestService.java:135)
```

This seemingly has the effect of deleting the questions on the original survey. The original groups are present when I view the survey, but none of the questions are there.

Should we just chalk this up to the survey being too large and we don't support that many option questions/options?

**Comment by muloem** [comment] 2015-11-02 20:43
@rumca yes I think that is what we should do for now.  Later we can figure out a reasonable but acceptable size with which to stress test the system.

**Comment by rumca** [comment] 2015-11-03 11:07
Disregard my previous comment, seems this is unrelated to the copying functionality. A survey with 25 questions each with 100 options will always through the above exception when trying to display them.

**Comment by rumca** [comment] 2015-11-03 12:30
Everything looks OK with the below steps:

* Set up a survey with two groups of 5 option questions, each with 100 options
* Copy the survey
* Verify the copy has all questions
* Verify no duplicates in original

@muloem is this enough to close this issue?

**Comment by muloem** [comment] 2015-11-03 12:58
@rumca yes I think this is enough for this release.

**Closed** 2015-11-03 13:00 UTC
Labels: 1 - Bug, 2 - Fixed
