### ISSUE TITLE
User tab does not render in Firefox 41

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1445] opened 2015-10-21 06:42 UTC
This is due to a [Clojurescript compiler bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1138325). Updating the compiler to a more recent version should resolve the issue.

## Testplan

* Open the User tab in Firefox v.41 or later and Safari. The page should render correctly.
* **note**: There are some new warnings emitted when building the dashboard but [these should be harmless](https://groups.google.com/d/msg/clojure/o7AF4XeksZ4/6N4iKnxsCwAJ) and will be resolved next time we bump the compiler version.

**Comment by akvotender** [comment] 2015-10-23 08:03
Assigned to [Tender discussion #6077](http://flowhelp.akvo.org/discussions/problems/6077-adding-a-user).

**Comment by Geerts** [comment] 2015-10-26 09:37
The same issue has been reported in Safari as well (http://flowhelp.akvo.org/discussions/problems/6077-adding-a-user). However, I was not able to reproduce this.

**Comment by akvotender** [comment] 2015-10-26 09:52
Assigned to [Tender discussion #6087](http://flowhelp.akvo.org/discussions/problems/6087-browser-issues).

**Comment by rumca** [comment] 2015-11-01 19:46
The users tab loads & functions correctly on both firefox and safari.

**Closed by rumca** 2015-11-01 19:46 UTC
Labels: 1 - Defect, 2 - Fixed

**Comment by akvotender** [comment] 2015-11-04 12:39
Assigned to [Tender discussion #6161](http://flowhelp.akvo.org/discussions/problems/6161-no-subject).
