### ISSUE TITLE
After using data cleaning to modify response data the API still returns old data to Android device

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#1839] opened 2016-11-23 09:14 UTC
There was an issue for akvo-flow-mobile:
https://github.com/akvo/akvo-flow-mobile/issues/451

It turns out the api is returning the old value. The dashboard has the correct value.

Steps to reproduce:
On dashboard create a monitored survey with just one text question for example "why?"
Once assigned the survey to your device create an answer for example "bc" and send it.
Using dashboard data cleaning export the excel, modify the answer to "because" and reimport it.
The dashboard now shows the correct answer.
Sync the datapoints on your device (using menu option "sync")
Open that entry you will see the answer is the old one: "bc".
In the logs you will see that the api returns something like this:

`{"surveyedLocaleData":[{"displayName":"","id":"7975-8kjs-e90d","identifier":null,"lon":null,"surveyGroupId":145192019,"lastUpdateDateTime":1479827303508,"lat":null,"surveyInstances":[{"qasList":[{"q":"147092013","a":"bc","t":"FREE_TEXT"}],"collectionDate":1479827149202,"uuid":"a9b51b74-31fa-4ee1-8ce9-bb419a40f668","surveyId":148092013,"submitter":"valeria_api19_tablet"}],"keyId":null}],"message":null,"offset":0,"code":"200","resultCount":1}`

I searched for the QuestionAnswerStore and it is the new value that shows. I also tried deleting the memcache but still the api returns the old value.

**Comment by stellanl** [comment] 2016-11-25 09:43
AFAIK, the API does not read from the QuestionAnswerStore table, but the surveyalValue table.

**Comment by janagombitova** [comment] 2017-08-31 12:11
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-71638-from-nikki-at-akvo-dot-org

**Comment by muloem** [comment] 2017-08-31 12:19
@janagombitova So we are planning to sort this out for the next release. the issue is #2229

**Comment by janagombitova** [comment] 2017-08-31 13:26
@muloem  Ah nice. The partner will be so happy how quick we are in resolving issues. The machine is rolling well

**Comment by janagombitova** [comment] 2017-09-11 09:18
I have tested this issue after the hotfix release as it was linked to #2229 to check if it is still a problem. I have cleaned a number question and a geolocation (use as point location) question and synced in the points. In the History the answers updated correctly, but on the Map the points were still showing in the old location (for all points and for the individual location of the points). So I deleted all submissions from my device and synced in data points again. The points still show in the wrong location. I have created a new issue in flow-mobile:  https://github.com/akvo/akvo-flow-mobile/issues/869 and this one can be considered resolved.

**Comment by muloem** [comment] 2017-11-06 05:27
Reopening this issue do to the fact that data point location that is sent to the devices is not updated after data cleaning

**Comment by muloem** [comment] 2017-11-13 09:29
# Test Plan 

1. For an existing monitoring survey, take a look at the map and select a data point.  Note its location 

2. Download the raw data spreadsheet for the registration form, and edit the geo question that should correspond to the location 

3. Update the latitude and longitude of the geo question to a different known location and upload the raw data spreadsheet

4. When the upload is completed, verify that the data point indeed shows in the new location

5. Assign the survey to a device and sync the data points 

6. Verify that the datapoint is also shown in the correct location on the app

**Comment by janagombitova** [comment] 2017-11-27 14:41
I checked on the app and the location is updated. 👍 

On the Carto map, my data cleaning changes were reflected but the location one not. I want to cross check this more thoroughly, so will create a separate issue. These changes are ready to roll

**Closed** 2017-11-30 14:03 UTC
Labels: Ready for release
