### ISSUE TITLE
Show surveys in alphabetical order on export reports

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-flow#1134] opened 2015-02-06 15:17 UTC
See for example on http://cwsa.akvoflow.org/admin/: In the survey overview they are nicely sorted, however when selecting from the dropdown when exporting a report it's not sorted.

**Comment by janagombitova** [comment] 2016-01-19 15:08
could not reproduce this issue as in all drop-downs all surveys are in alphabetical order. Closing issue

**Closed by janagombitova** 2016-01-19 15:08 UTC
