### ISSUE TITLE
Cartodb custom maps - action icons inconcistently displayed

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1668] opened 2016-05-12 07:44 UTC
Edit/Delete action icons should only be displayed for maps that are based on surveys that the logged in user has relevant access rights for

**Comment by janagombitova** [comment] 2016-06-09 09:01
The expected behaviour of the 'edit' and 'delete' icons for the MVP is that they will always be shown to all user for all created custom maps in the list of maps as well while the user is viewing a created map. 

We will create a general permission for creating these maps, that will hold the view, edit, delete and create permissions. If a user does not have the permission, the tab Custom maps will simply not be shown. The only open question that is permission related is to obey the 'view data' permission that links to data submitted for a particular survey. This is handled and explained in a separate issue. 

Regarding this issue @kymni I have done some testing a realised that the icons are not shown for a created map when the map only has the name (and/or description) added to it. Once you base a map on a survey the actions are shown.

**Comment by kymni** [comment] 2016-06-09 10:19
@janagombitova replicated, issue is that current logic dictates that if a survey/form is not selected, then the action icons are not displayed. Fix is to disable saving a map unless a survey/form is selected

**Comment by janagombitova** [comment] 2016-06-09 12:08
I see, because it does not make sense to be able to save something that you cannot delete or edit afterwards. So then we should just add in the 'save' button logic that it will not be enabled until you add the name and select a survey > form at least (not description - that is optional and not questions as they do not apply for monitored forms) 

What do you think @kymni and should we create a new issue to handle the 'save' button logic?

**Comment by janagombitova** [comment] 2016-06-21 14:29
Issue seems solved by applying the 'save' logic. All created maps have both action icons visible and functioning as expected.

**Comment by janagombitova** [comment] 2017-04-06 14:17
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.

**Closed by janagombitova** 2017-04-06 14:17 UTC
Labels: 1 - Maps
