### ISSUE TITLE
Detail view in Monitoring does not show the difference between forms

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1298] opened 2015-06-10 12:58 UTC
In Monitoring once the user decides to view details of one update the popup screen shows the list of the ID, Survey, Submitter, Device Collected and Action. In the Survey column all the forms appear to be the same form filled in multiple times. However that is not the case and one of the forms is the Registration form. This is not visible in the Survey path because the name is not displayed properly.

Example screen shot:
All the Surveys have the same path: /Safi Sana/waste/waste truck/update truck driver. But the last one is not the "update truck driver" form but the registration form named "intake"

![screen shot 2015-06-10 at 14 54 39](https://cloud.githubusercontent.com/assets/12456965/8082836/a487ae90-0f80-11e5-8ad5-a95af547f60d.png)

**Comment by joycarpediem** [comment] 2015-07-07 15:55
Duplicate of #1244

**Closed by joycarpediem** 2015-07-07 15:56 UTC
Labels: 1 - Bug, 3 - UI, Quick Fix
