### ISSUE TITLE
Perform survey integrity check at publish time

### ISSUE THREAD

**Issue by ghost** [akvo/akvo-flow#1218] opened 2015-04-01 10:05 UTC
When we publish a survey, we should at that time check it's integrety:

1) questions that are dependent on a question that comes later
2) dependent questions dependent on non-existing options
3) presence of cascades
4) etc.

**Comment by janagombitova** [comment] 2018-02-15 10:59
Duplicate of https://github.com/akvo/akvo-flow/issues/1324

**Closed by janagombitova** 2018-02-15 10:59 UTC
Labels: 1 - Surveys
