### ISSUE TITLE
Duplicate Column names generated in raw data

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#2315] opened 2017-11-14 06:38 UTC
## Usecase:
In a lot of cases , particularly in agriculture, there are instances where an entity may own more that one assets that need to be geolocated.
Ex: A farmer may have multiple plots of land where he grows different crops. This is a common practice to hedge your bets on part of the farmer. 
In these cases multiple geolocation questions are added to the form and displayed conditionally.

## Steps:
Create a form with more that one Geolocation questions
Download a raw data spreadsheet for the form

Issue:
![image](https://user-images.githubusercontent.com/4419787/32766162-a33d38dc-c948-11e7-99e9-9463f4098c10.png)
The cordinates and other GPS data is split across 4 columns (Latitude/Longitude/Elevation/Geo Code) but the question Key is only appended to the Latitude column.
This results in duplicate column names.
A lot of external systems (including Cartodb) imposes restrictions on duplicate column names.

## Possible solution:
Append the question Key to all geolocation columns, like we do for the latitude data, to ensure consistency an non-duplicate column headers.

**Comment by janagombitova** [comment] 2017-11-14 16:16
The changes should also reflect the Data analysis exports (currently known as raw data reports with Advance settings)

**Comment by stellanl** [comment] 2017-12-06 14:19
1. we now have DATA_CLEANING, DATA_ANALYSIS and COMPREHENSIVE reports. Which should have unique column names for geodata?
 2. Should we also do this for "split" option columns, which are similar? Different issue?
 3. Should we also do this for photos, which have similar long and lat columns? Different issue?

**Comment by janagombitova** [comment] 2017-12-15 11:42
hey @stellanl how are you thinking of addressing the issue? 

Not sure if I am not to late to the party but here are my comments to your questions: 
1. Data cleaning and Data analysis should have unique columns. How the data is shown in Comprehensive is something we need to reconsider as we have a "third" way of showing data there and we should unify it with one of the two structures, but that is a different discussion. 
2. and 3. If you add the question name/ID to the header then I assume you can apply the rule also for options, cascades, caddisfly, photo. But not sure how you want to handle this issue. And not sure if we need separate issues for each case. @muloem  what do you think?

**Comment by stellanl** [comment] 2017-12-15 14:30
Doing it for data cleaning is more work, since the import needs to be changed a bit, too. A corner of the current import algorithm relies on all "extra" columns starting with "--GEO".

When it comes to columns the comprehensive report is very like data cleaning.

**Comment by janagombitova** [comment] 2017-12-18 16:27
A bit more thoughts on this from my side: 

I went back to the question: Why did we create the separate concepts of Data cleaning exports and Data analysis exports. Data cleaning exports are meant to be read by users and used in Excel. Data analysis exports are made to be imported into another tool and analysed there. In this step of the workflow is when the problem of not having unique cell headers occurs. Taking this thinking into consideration it is ok to make sure the headers are unique for only Data analysis exports that also do not hold the question IDs needed for cleaning. 

On the other hand what happens if a user using the Data cleaning export and has multiple geolocation questions and reorders the columns? How will she know which Long column is which question? 

On the other hand is the concern for having a consistent pattern in handling headers. The headers do not need to be identical as the sheets are used for different purposes, but we should ensure we use the same rules when creating them. 

I think we need to make sure we ensure: 
- columns do not get mixed 
- give enough information but not too much 

Curious to hear your thoughts and ideas

**Comment by stellanl** [comment] 2017-12-19 14:11
Right now we do not support "extra" columns being moved around before an import. They must immediately follow the "primary" column, in the same order as exported.

**Comment by stellanl** [comment] 2017-12-21 13:51
We can certainly change the data cleaning format so all columns are unique, and even allow the user to move them around arbitrarily. Takes about an hour each to code the changes for export and import.

**Comment by muloem** [comment] 2018-01-09 09:23
I am really late to the party but given that the issue is affecting the data analysis reports, we should address it there and only if it becomes an issue for the data cleaning reports should we consider fixing it there as well.

**Comment by janagombitova** [comment] 2018-01-09 09:34
Sounds good to me, I realised we should be strict about the difference between the Data cleaning export and the Data analysis one also in other changes. And this is a mindset I also need to get used to. But to conclude I agree. Let's tackle the Data analysis one first to have users learn to use that one for the cases of using Flow data in other tools or for further analysis.

**Comment by muloem** [comment] 2018-01-09 13:46
Looking at the implementation, something has occurred to me.  We explicitly created the data analysis report to be used for external systems and we generate this in two ways

1. if there are variable names (question ID) assigned to the question, the column header is `variableName` and for cases like the geo question `variableName_Latitude` etc

2. if there are no variable names then we use the question text e.g. `question 1 of group 3`. 

So I am wondering since we are anyway intending to use the export for an external system, why we don't create default variable names incase one isn't assigned. e.g. `question_1_3` for question 1in group 3?

@stellanl @janagombitova

**Comment by janagombitova** [comment] 2018-01-09 15:09
@muloem Do you suggest always for Data analysis exports create "default variable names"? For example:  I have 2 questions in my form: What is your name? and How old are you?. Instead of showing the question text `What is your name?` and `How old are you?`in the headers, show `question_1`and `question_2`or show `What_is_your_name` and `How_old_are_you`? 

If the first then I do not think this would be of value to users as it would then require the person working with the data to also have the form with him to make sense of what he is looking at. 

Secondly, if we want to consider default variable names for the Data analysis export then we should in a different issue.

**Comment by muloem** [comment] 2018-01-10 05:25
> Do you suggest always for Data analysis exports create "default variable names"? 

Yes, thats exactly the idea.

> If the first then I do not think this would be of value to users as it would then require the person working with the data to also have the form with him to make sense of what he is looking at.

Exactly.  Since we are doing data analysis, the person will most likely always be using the form e.g from the discussion with Claire.  Only having the question text doesn't tell enough when doing data analysis.

> Secondly, if we want to consider default variable names for the Data analysis export then we should in a different issue.

Agreed.  We should explore it in a different issue but I wanted to raise it here to point out that this approach would also resolve this issue in quite a similar way to how we are doing it here.  Except here we are using the question key id whereas a variable name would address the issue

**Comment by stellanl** [comment] 2018-01-10 07:53
This was discussed in #2170, too

**Comment by janagombitova** [comment] 2018-01-12 12:37
I have created a separate issue; https://github.com/akvo/akvo-product-design/issues/290 where we can talk more about the value of such a change and research with users

**Comment by janagombitova** [comment] 2018-01-24 10:55
In Data analysis export we now have the structure of question text - latitude or variable name - latitude to ensure no columns have duplicated headers. Data cleaning export remained untouched as agreed. 

<img width="878" alt="screen shot 2018-01-24 at 11 54 20" src="https://user-images.githubusercontent.com/12456965/35328695-7d0bdafa-00fd-11e8-8522-5d99ae661840.png">

👍  fix ready for release

**Closed** 2018-01-26 10:05 UTC
Labels: 1 - Reports, Ready for release
