### ISSUE TITLE
Changing question type leads to incorrect data point name definition

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3412] opened 2020-02-12 09:52 UTC
# Context
Changing the question type could lead to _invalid_ question configuration.

# Problem or idea
A user can set a question to be used as part of the "Datapoint name" by selecting the option _Use as data point name_
![2020-02-12_865x102_scrot](https://user-images.githubusercontent.com/178474/74322015-87a4cb00-4d83-11ea-8f24-55863f8995ab.png)
In this case the question type is "Text".

A geolocation question can be used to be the "Datapoint location" by selecting the option _Use as data point location_
![2020-02-12_846x108_scrot](https://user-images.githubusercontent.com/178474/74322104-b7ec6980-4d83-11ea-99aa-2a1fb120315c.png)

If a user with a question type _Text_ selects the option "Use as data point name" and then changes the question type to _Geolocation_ and selects the option "Use as data point location" the question ends up with the 2 flags enabled.

When using the published form, the App user ends up with Data point names that contain the _raw_ values of the Geolocation.
![2020-02-12_584x652_scrot](https://user-images.githubusercontent.com/178474/74322719-a8b9eb80-4d84-11ea-82d7-682a3a4f6581.png)

# Solution or next step

* Make sure a Geolocation question can't be used as part of the data point name
* _Whitelist_ the question types that can be used as data point name

**Comment by muloem** [comment] 2020-02-12 11:01
This is a duplicate of https://github.com/akvo/akvo-flow/issues/1692. Closing the other one.

**Comment by iperdomo** [comment] 2020-02-12 11:16
###  Test case
* Create a question use _Text_ as type, and select _Use as data point name_
* Save it
* Change the question type to _Gelocation_ and select _Use as data point location_
* Save it
* The other flag _Use as data point name_ must be de-selected
* Change it back again to _Text_ and _Use as data point name_
* Save it
* The other flag _Use as data point location_ must be de-selected

**Comment by iperdomo** [comment] 2020-02-12 12:48
Attached a couple of executions on UAT1, before and after the fix: [uat1.har.zip](https://github.com/akvo/akvo-flow/files/4192117/uat1.har.zip)

`.har` files can be viewed on https://toolbox.googleapps.com/apps/har_analyzer/

*  `localeNameFlag` can't be true if the question type is geolocation
*  `localeLocationFlag` can't be true if the question type is **not** geolocation

**Closed** 2020-02-18 11:34 UTC
Labels: 1 - Surveys, UI
