### ISSUE TITLE
Cluster re-computation fails on missing geocells property on SurveyedLocale

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#556] opened 2014-05-30 15:04 UTC
If a SurveyedLocale doesn't have `latiude|longitude` attribute, no `geocells` can be calculated, leading to a `NullPointerException` when trying to use the latter mentioned property.

Side note: The computation should be made using a backend

**Comment by janagombitova** [comment] 2016-09-27 15:02
@mulo is this still relevant?

**Comment by janagombitova** [comment] 2019-08-08 06:41
Closing this issue as we no longer use clustering of data points. It can always be opened if I misunderstood the problem and the issue is still relevant

**Closed by janagombitova** 2019-08-08 06:41 UTC
