### ISSUE TITLE
Maps tab does not show the entire map

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1283] opened 2015-05-29 09:36 UTC
To reproduce (in chrome or firefox):

* Go to the survey tab
* Scroll down a little
* Go to the maps tab
  * The map is also scrolled down which hides some of the controls
* Go back to the survey tab and scroll to top
* Go back to the maps tab
  * The map renders fine

**Comment by loicsans** [comment] 2015-05-29 12:33
I really cannot replicate this, on any browser.

**Comment by joycarpediem** [comment] 2015-07-07 09:27
@jonase , can you help @gabemart to simulate this issue

**Comment by gabemart** [comment] 2015-07-10 10:45
@joycarpediem @jonase I can replicate on OSX 10.10.3 using either Chrome or Safari

On Ubuntu, neither Chrome or FF show this behavior.

I will look into the cause

**Comment by gabemart** [comment] 2015-07-10 12:06
After some more testing, this is issue is *not* triggered by browser or operating system, as I previously thought, but on viewport size. I can reliably reproduce on a 1200px * 700px viewport

**Comment by gabemart** [comment] 2015-07-14 10:00
There are two issues with the map:

The first issue is that when navigating to the maps tab with i) a viewport less than about 750px high and ii) a scrollbar position that is not at the very top, the map controls are not visible.

http://gfycat.com/LeadingHardGreatdane

The second issue that when hitting a zoom control on a viewport less than about 750px high, the page scrolls such that the map controls are in the top-left corner of the page, which is **underneath** the header bar and is thus inaccessible to the user.

http://gfycat.com/SafeVeneratedDove

The first issue can be solved simply by using javascript to scroll to the top of the viewport whenever the Maps tab is loaded. 

In order to fix the second issue, I suggest:

For the Maps tab, display the header navigation menu as a regular element, rather than having it be fixed to the top of the viewport. This will prevent the map controls being hidden under the navigation menu.

However, this can make navigation tricky on small viewport devices, because trying to scroll up to view the navigation menu will zoom the map rather than scroll the page. Therefore I suggest we disable scroll-to-zoom for the Maps tab entirely, and only allow zooming the map via the zoom controls in the upper left.

Thoughts?

**Comment by janagombitova** [comment] 2015-07-14 11:18
@joycarpediem Is this a compelling enough issue to invest time in it knowing that these things will be fixed with the cartoDB integration? So my question is, can this issue stand for one more month?

**Comment by joycarpediem** [comment] 2015-07-14 15:49
@janagombitova , i agree it is not a critical enough issue and we'll be redesigning the page shortly anyways

**Comment by gabemart** [comment] 2015-08-05 11:52
Removing my assignment for now as we don't plan to address this until the page is redesigned

**Comment by gabemart** [comment] 2015-12-16 16:05
@janagombitova I'm not sure that disabling scrolling on the page is the best way to combat this issue. Personally, I think that disabling scroll-to-zoom on the map is a better solution. The map can still be scrolled in and out using the zoom buttons

**Comment by rumca** [comment] 2015-12-30 19:29
@gabemart do the commits for this still need merged to release/1.9.4?

**Comment by rumca** [comment] 2016-01-03 23:52
code merged to release candidate and the above issue is no longer a problem :+1:

**Closed by rumca** 2016-01-03 23:52 UTC
Labels: 3 - Maps, 3 - UI, Quick Fix
