### ISSUE TITLE
A question can not be dependent on 'other' option

### ISSUE THREAD

**Issue by Anna-Marthe** [akvo/akvo-flow#824] opened 2014-10-03 07:54 UTC
When an option question has been designed with the option (tick box) other, there can be no follow-up dependent question referring to that. Is that an intentional thing? There is a way around it of course by creating your own 'other' option, and then referring to it.

**Comment by mtwestra** [comment] 2015-01-26 11:06
Duplicate of [#372]

**Closed by mtwestra** 2015-01-26 11:06 UTC
