### ISSUE TITLE
Reduce occurence of Internal Server Error

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#1830] opened 2016-11-11 12:30 UTC
While debugging this issue on mobile https://github.com/akvo/akvo-flow-mobile/issues/474
I have found that the api service surveylocale the response takes too long to complete on the backend, here is the trace:

[error500_surveyedlocale.txt](https://github.com/akvo/akvo-flow/files/585770/error500_surveyedlocale.txt)

My suggestion would be maybe to decrease the number of requested entries from 300 to 150. 

The complete log for this issue can be found on dev2.

**Comment by muloem** [comment] 2017-08-18 14:28
The error is caused by a `DeadlineExceededException` and the synchronisation task is cancelled. if we look at the `/surveyedlocale` endpoint, we are querying for the response values in an inefficient way i.e. querying for the responses for each of 300 datapoints one-by-one.  A more optimal solution would be to query for the responses in batches to reduce the number of queries to the datastore.

See https://github.com/akvo/akvo-flow/blob/develop/GAE/src/org/waterforpeople/mapping/app/web/SurveyedLocaleServlet.java?utf8=✓#L128-L142

**Comment by janagombitova** [comment] 2017-09-06 15:09
Issue resolved with the fixes here: https://github.com/akvo/akvo-flow/issues/2238

**Closed by janagombitova** 2017-09-06 15:09 UTC
Labels: Backlog
