### ISSUE TITLE
Ability to collect polygon and line data

### ISSUE THREAD

**Issue by henryjewell** [akvo/akvo-flow#339] opened 2013-08-22 13:34 UTC
As a FLOW user, I would like to be able to collect polygon data. This would be very useful for mapping and monitoring entities that are not points, such as an open defecation zone or a river basin to name just two. In addition it would also be an advantage to be able to do path tracking to get accurate assessment of walking distance to water source for example (this would be more accurate than a straight line calculation). In summary it would be great to have the functionality to collect polygon and line data in addition to point data.

**Comment by mtwestra** [comment] 2015-01-13 12:42
duplicate of https://github.com/akvo/akvo-flow/issues/1012 and https://github.com/akvo/akvo-product-design/issues/66

**Closed by mtwestra** 2015-01-13 12:42 UTC
Labels: 1 - New Feature, 2 - Discussion
