### ISSUE TITLE
Cartodb custom maps - map description change not detected 

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1710] opened 2016-06-15 07:38 UTC

**Comment by janagombitova** [comment] 2016-06-21 13:23
**Test case I followed**
1. Create a new custom map and add a description to it
2. Go back to the list of map and the new map should be on the top of the list
3. Click on the 'edit' icon > brings you to the edit screen 
4. Change the description of the map and save 
5. Go back to list of maps and check that the description of the map reflects the changes made 

Could not reproduce the problem, thus issues seems fixed

**Comment by janagombitova** [comment] 2017-04-06 14:19
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.

**Closed by janagombitova** 2017-04-06 14:19 UTC
Labels: 1 - Maps
