### ISSUE TITLE
Text in in-line help box for French and Spanish versions does not fit

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1462] opened 2015-11-03 14:51 UTC
Under the Devices tab we have added an in-line help text next to the IMEI, for the Spanish and French versions the last parts of the text is missing. This is probably due to the size of the box. 

<img width="530" alt="screen shot 2015-11-03 at 15 46 45" src="https://cloud.githubusercontent.com/assets/12456965/10910897/582e44f2-8242-11e5-8a0c-51954be12515.png">

**Comment by gabemart** [comment] 2015-12-09 16:30
I can only reproduce on the French translation. I think the problem is being caused by double-quotes in the translated string. The string is injected into a double-quote-terminated title attribute, and the presence of the double quote in the string terminates the string early.

E.g. if the string were `My name is "Gabe"` then the markup in the browser would be `title="My name is "Gabe"` and the hover text would become "My name is" as a result.

Permanent fix: replace every instance of a `"` with `&quot;` in the language files programmatically

Temporary fix for this one string: replace `"` with `&quot;` manually

**Comment by gabemart** [comment] 2015-12-09 16:37
#Test plan

1) Set the language to French

2) Navigate to the 'Devices' tab

3) Hover over the `?` icon next to the 'IMEI' header. Verify that the text ends with `[...] Identity Number`

**Comment by gabemart** [comment] 2015-12-21 12:13
There is a new pull request to solve this issue programmatically (in case tooltip text includes double-quotes in the future). The existing test plan can still be used for the new fix.

**Comment by rumca** [comment] 2016-01-04 09:37
Test plan passes as described

**Closed by rumca** 2016-01-04 09:37 UTC
Labels: 2 - Fixed, 3 - UI, Quick Fix
