### ISSUE TITLE
FIND button in the Data tab is partially hidden when statistics feature enabled

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#874] opened 2014-10-27 12:24 UTC
The changes related to enabling filtering based on sub country regions (see https://github.com/akvo/akvo-flow/issues/229) result in the *FIND* button hidden when this functionality is enabled.

![screen shot 2014-10-27 at 13 23 36](https://cloud.githubusercontent.com/assets/533336/4790671/21c94ce2-5dd4-11e4-8a37-f0252b632cec.png)

**Comment by joycarpediem** [comment] 2015-06-23 03:55
Duplicate of #1314

**Closed** 2015-07-13 07:54 UTC
Labels: 1 - Defect, 3 - UI
