### ISSUE TITLE
Forms not opening when navigating to the survey

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1701] opened 2016-06-07 15:37 UTC
When navigating to the survey the form does not unfold. After clicking on the title the form actually shows up. 

Could not reproduce on live dashboards. 

- 1.9.8 UAT Folder 
- 1.9.8 MF Surveys 
- 1.9.8 MF Survey
- Chrome 51.0.2704.79

![formmissing](https://cloud.githubusercontent.com/assets/13657774/15864126/1200e414-2cd6-11e6-83b2-ea5ad299ab7f.gif)

**Comment by janagombitova** [comment] 2016-06-08 10:31
@Geerts I could not reproduce this issue no matter how hard I tried... Will close it for now and lets reopen it again once we can find a pattern

**Closed by janagombitova** 2016-06-08 10:31 UTC
