### ISSUE TITLE
Changing the registration survey should be communicated to phone

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1078] opened 2015-01-14 14:15 UTC
How to reproduce:
1) create a monitoring survey with 2 forms, A and B
2) first make form B the monitoring form
3) send the forms to the device
4) now make form A the monitoring form
5) this is not seen as a change to the forms, so this change is not automatically downloaded by the device. Therefore, the whole survey needs to be deleted and reloaded

Proposed solution: changing the monitoring survey should be communicated to the device automatically, without the need for download. This may need an automatic republishing, for example.

**Comment by ichinaski** [comment] 2015-06-25 09:08
If the registration survey is changed, the subsequent survey sync requests to `/surveymanager?action=getAvailableSurveysDevice` will contain the new registration survey id.

As far as I understand, this should automatically happen in the backend. (This is pretty easy to check just issuing a few requests to the URL I pointed out). However, the current app implementation will not update the form, since it will consider the form up-to-date.

My proposal is to take the simplest route, and instead of using a new endpoint, survey republishing, etc, it should be just the app the one updating all the content.

That being said, existing data in the app can be misleading, if the former registration form has been used already.

**Comment by ichinaski** [comment] 2015-06-25 10:19
I can confirm the assignment is updated once the registration form is modified (and saved). @mtwestra shall we close this issue and handle it at https://github.com/akvo/akvo-flow-mobile ?

**Closed** 2017-02-23 12:42 UTC
Labels: Defect
